collectionFilename: test.cpp spring
cutoffDay: 27/07/2020 11:30
endDay: 25/07/2020 11:30
moduleCode: cs4115
penaltyPerDay: 1
startDay: 22/07/2020 11:30
tests:
  attendance:
    marks: 1
    tag: attendance
  compilation:
    command: g++ -std=c++0x -o test test.cpp
    marks: 2
    tag: compilation
  test1:
    answerFile: F:/PyCharmProjects/handin-ul/misc/c18111521/answer.txt
    command: test
    filterCommand: perl filter.pl
    filterFile: F:/PyCharmProjects/handin-ul/misc/c18111521/filter.pl
    inputDataFile: F:/PyCharmProjects/handin-ul/misc/c18111521/dataInput.txt
    marks: 3
    tag: test 1
totalAttempts: 10
weekNumber: w01