collectionFilename: test.cpp
cutoffDay: 20/07/2020 11:14
endDay: 09/07/2020 11:14
moduleCode: cs4115
penaltyPerDay: 1
startDay: 09/07/2020 11:14
tests:
  attendance:
    marks: 1
    tag: attendance
  compilation:
    command: g++ -std=c++0x -o test test.cpp
    marks: 2
    tag: compilation
  test1:
    command: test
    inputDataFile: F:/PyCharmProjects/handin-ul/misc/c18111521/dataInput.txt
    marks: 3
    tag: test 1
totalAttempts: 10
weekNumber: w02
