# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'access_rights_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 60, 71, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 57, 15))
        self.label_2.setObjectName("label_2")
        self.userEdit = QtWidgets.QLineEdit(Dialog)
        self.userEdit.setGeometry(QtCore.QRect(130, 60, 201, 21))
        self.userEdit.setObjectName("userEdit")
        self.modulesBox = QtWidgets.QComboBox(Dialog)
        self.modulesBox.setGeometry(QtCore.QRect(130, 130, 161, 21))
        self.modulesBox.setObjectName("modulesBox")
        self.user_error = QtWidgets.QLabel(Dialog)
        self.user_error.setGeometry(QtCore.QRect(130, 90, 201, 16))
        self.user_error.setText("")
        self.user_error.setObjectName("user_error")
        self.error_message = QtWidgets.QLabel(Dialog)
        self.error_message.setGeometry(QtCore.QRect(50, 200, 301, 16))
        self.error_message.setText("")
        self.error_message.setObjectName("error_message")
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setGeometry(QtCore.QRect(250, 240, 111, 21))
        self.addButton.setObjectName("addButton")
        self.removeAccess = QtWidgets.QCheckBox(Dialog)
        self.removeAccess.setGeometry(QtCore.QRect(160, 240, 85, 21))
        self.removeAccess.setObjectName("removeAccess")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Module Access Rights"))
        self.label.setText(_translate("Dialog", "User:"))
        self.label_2.setText(_translate("Dialog", "Module:"))
        self.addButton.setText(_translate("Dialog", "Add Access"))
        self.removeAccess.setText(_translate("Dialog", "Remove"))
