# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'handin_admin_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 300)
        MainWindow.setMinimumSize(QtCore.QSize(500, 300))
        MainWindow.setMaximumSize(QtCore.QSize(500, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 40, 200, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_user = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_user.setGeometry(QtCore.QRect(140, 100, 200, 30))
        self.pushButton_user.setObjectName("pushButton_user")
        self.pushButton_access_rights = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_access_rights.setGeometry(QtCore.QRect(140, 160, 200, 30))
        self.pushButton_access_rights.setObjectName("pushButton_access_rights")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Handin System (Administrator)"))
        self.pushButton.setText(_translate("MainWindow", "Create New Module"))
        self.pushButton_user.setText(_translate("MainWindow", "Create New User"))
        self.pushButton_access_rights.setText(_translate("MainWindow", "Module Access Rights"))
