collectionFilename: mtrans.cc
cutoffDay: 15/07/2020 14:50
endDay: 08/07/2020 14:50
moduleCode: cs4115
penaltyPerDay: 1
startDay: 08/07/2020 14:50
tests:
  attendance:
    marks: 1
    tag: attendance
  compilation:
    command: g++ -std=c++0x -o mtrans mtrans.cc
    marks: 2
    tag: compilation
  test1:
    command: ---
    marks: 3
    tag: test 1 ...
  test2:
    command: xxxx
    marks: 3
    tag: test 2 ...
totalAttempts: 10
weekNumber: w01
