collectionFilename: mtrans.cc
cutoffDay: 06/07/2020 16:21
endDay: 02/07/2020 16:21
moduleCode: cs4115
penaltyPerDay: 2
startDay: 01/07/2020 16:21
tests:
  attendance:
    marks: 1
    tag: attendance
  compilation:
    command: g++ -std=c++0x -o mtrans mtrans.cc
    marks: 2
    tag: compilation
  test1:
    command: xxx===
    marks: 3
    tag: test 1
  test2:
    command: xxx-------
    marks: 3
    tag: test 2
totalAttempts: 10
weekNumber: w01
