cutoffDay: 6/29/2020 12:00 AM
endDay: 6/29/2020 12:00 AM
moduleCode: cs4115
penaltyPerDay: 1
startDay: 6/29/2020 12:00 AM
weekNumber: w01


# TODO: new configs - add them to lecturer.py
totalAttempts: 10
