collectionFilename: test.cpp
cutoffDay: 25/07/2020 12:45
endDay: 20/07/2020 12:45
moduleCode: cs4115
penaltyPerDay: 1
startDay: 15/07/2020 12:45
tests:
  attendance:
    marks: 1
    tag: attendance
  compilation:
    command: g++ -std=c++0x -o test test.cpp
    marks: 2
    tag: compilation
  test1:
    answerFile: F:/PyCharmProjects/handin-ul/misc/c18111521/dataInput.txt
    command: test
    filterFile: ''
    inputDataFile: F:/PyCharmProjects/handin-ul/misc/c18111521/dataInput.txt
    marks: 3
    tag: test1
totalAttempts: 10
weekNumber: w01
